# Generated by Django 4.2 on 2024-12-11 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The title of the survey.", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="A brief description of the survey."
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Unique identifier for the survey.",
                        max_length=225,
                        unique=True,
                    ),
                ),
                (
                    "is_editable",
                    models.BooleanField(
                        default=True,
                        help_text="Can the survey be edited after creation?",
                    ),
                ),
                (
                    "allow_multiple_submissions",
                    models.BooleanField(
                        default=False,
                        help_text="Allow users to submit the survey multiple times.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey",
                "verbose_name_plural": "Surveys",
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="survey.survey"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who submitted this answer.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Answer",
                "verbose_name_plural": "User Answers",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(help_text="The question text.", max_length=500),
                ),
                (
                    "field_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Text"),
                            (2, "Number"),
                            (3, "Radio"),
                            (4, "Select"),
                            (5, "Multi-Select"),
                            (6, "Textarea"),
                            (7, "URL"),
                            (8, "Email"),
                            (9, "Date"),
                            (10, "Rating"),
                        ],
                        help_text="The input type for the question.",
                    ),
                ),
                (
                    "options",
                    models.TextField(
                        blank=True,
                        help_text="Options for 'Radio', 'Select', or 'Multi-Select', separated by commas.",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Is this question mandatory?"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="The order of the question in the survey."
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="survey.survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.TextField(
                        help_text="The value provided by the user for this question."
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="survey.question",
                    ),
                ),
                (
                    "user_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="survey.useranswer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
            },
        ),
    ]
