# Generated by Django 4.2 on 2024-12-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="published",
            field=models.BooleanField(
                default=False, help_text="Is the survey published?"
            ),
        ),
    ]
