# Generated by Django 4.2 on 2024-12-11 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("survey", "0002_survey_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                help_text="The user who created the survey.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
