# Generated by Django 4.2 on 2024-12-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_survey_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="field_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Radio"),
                    (2, "Select"),
                    (3, "Multi-Select"),
                    (4, "Textarea"),
                ],
                help_text="The input type for the question.",
            ),
        ),
    ]
