# Generated by Django 4.2 on 2024-12-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0004_alter_question_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="area",
            field=models.CharField(
                blank=True, help_text="The area/category for analysis.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="dimension",
            field=models.CharField(
                blank=True, help_text="The dimension for analysis.", max_length=200
            ),
        ),
    ]
