# Generated by Django 4.2 on 2024-12-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0005_question_area_question_dimension"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Optional: Password to access the survey.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="recipient_emails",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of email addresses that are allowed to access this survey.",
            ),
        ),
    ]
